---
title: "R Notebook"
output: html_notebook
---

```{r}
### Code for "Democratization and Economic Output in Sub-Saharan Africa"
### Daniel De Kadt and Stephen B. Wittels

## A note to users:
## Use setwd() to set the working directory to the location where data files are saved. 
## Figures are programmed to be saved automatically to the working directory.
## They are named according to their figure number in the paper.
## The three tables in the paper are saved as the objects "mali.weights," "panel.estimates," and
## "moderators." Code to print these objects to the console is included at the end.


## Options and Libraries
options(scipen = 6, digits = 3)

if (!require("pacman")) install.packages("pacman")
pacman::p_load(foreign, 
  Synth, 
  xtable, 
  rgenoud, 
  reshape2, 
  quadprog, 
  ucminf, 
  Rcgmin, 
  Rvmmin, 
  minqa, 
  Rcpp, 
  ggplot2, 
  plyr, 
  grid, 
  lme4,
  janitor,
  dplyr,
  CausalImpact  # For use in the extension
)

```


```{r}
## Data
load("afripanel_wdk_final.RData")
a <- read.csv("conditioning_variables1.csv")
panel.reg <- read.dta("panel.reg1.dta")
```

## Replication

```{r}
## Functions
synth.wdk1 <- function(
  unitID,
  fullname,
  begin,
  end,
  tr2,
  final,
  low,
  high
){
  
  data <- afripanel[afripanel$WBCode==unitID | afripanel$cont_dem_ind==1,]
  
  controls <- unique(data$WBCode[data$WBCode!=unitID])
  
  prep <- dataprep(
    foo=data, 
    predictors=c(
      "lngdpmadlag",
      "lngdpmadlag2",
      "lngdpmadlag3",
      "lngdpmadlag4",
      "lnpop",
      "ki",
      "openk",
      "civwar",
      "civwarend",
      "pwt_xrate",
      "pwt_xrate_lag1",
      "pwt_xrate_lag2",
      "pwt_xrate_lag3",
      "wbank",
      "wbank_lag1",
      "wbank_lag2",
      "imfadj",
      "imfadj_lag1"
    ),
    dependent="lngdpmad",
    unit.variable="wbcode2",
    time.variable="year", 
    treatment.identifier=unitID, 
    controls.identifier=controls,          
    time.predictors.prior=c(begin:end),
    time.optimize.ssr=c(begin:tr2),
    time.plot=c(begin:final),
    unit.names.variable="WBCode"
  )
  
  out <- synth(prep)
  
  path.plot(synth.res=out, dataprep.res=prep,
            Ylab="Log GDP per capita", Legend=NA, tr.intake=tr2,
            Ylim=c(low,high) , Main=fullname
  )
  
  gap <- prep$Y1plot - (prep$Y0plot %*% 
                          out$solution.w)
  
  colnames(gap) <- unitID
  
  synth.table <- synth.tab(dataprep.res=prep, synth.res=out)
  
  print(xtable(synth.table$tab.w))
  
  print(xtable(synth.table$tab.v))
  
  tab <- cbind(prep$X1,prep$X0%*%out$solution.w)
  colnames(tab) <- c("Treated Unit","Synthetic Unit")
  print(tab)
  
  return(gap)
}
```

```{r}
synth.wdk2 <- function(
  unitID,
  fullname,
  begin,
  end,
  tr2,
  final,
  low,
  high
){
  
  data <- afripanel[afripanel$WBCode==unitID | afripanel$cont_dem_ind==1,]
  
  controls <- unique(data$WBCode[data$WBCode!=unitID&data$WBCode!="ETH"&data$WBCode!="SDN"])
  
  prep <- dataprep(
    foo=data, 
    predictors=c(
      "lngdpmadlag",
      "lngdpmadlag2",
      "lngdpmadlag3",
      "lngdpmadlag4",
      "lnpop",
      "ki",
      "openk",
      "civwar",
      "civwarend",
      "pwt_xrate",
      "pwt_xrate_lag1",
      "pwt_xrate_lag2",
      "pwt_xrate_lag3",
      "eximdiff",
      "eximdiff_lag1",
      "eximdiff_lag2",
      "wbank",
      "wbank_lag1",
      "wbank_lag2",
      "imfadj",
      "imfadj_lag1",
      "imfadj_lag2"
    ),
    dependent="lngdpmad",
    unit.variable="wbcode2",
    time.variable="year", 
    treatment.identifier=unitID, 
    controls.identifier=controls,          
    time.predictors.prior=c(begin:end),
    time.optimize.ssr=c(begin:tr2),
    time.plot=c(begin:final),
    unit.names.variable="WBCode"
  )
  
  out <- synth(prep)
  
  path.plot(synth.res=out, dataprep.res=prep,
            Ylab="Log GDP per capita", Legend=NA, tr.intake=tr2,
            Ylim=c(low,high) , Main=fullname
  )
  
  gap <- prep$Y1plot - (prep$Y0plot %*% 
                          out$solution.w)
  
  colnames(gap) <- unitID
  
  synth.table <- synth.tab(dataprep.res=prep, synth.res=out)
  
  print(xtable(synth.table$tab.w))
  
  print(xtable(synth.table$tab.v))
  
  tab <- cbind(prep$X1,prep$X0%*%out$solution.w)
  colnames(tab) <- c("Treated Unit","Synthetic Unit")
  print(tab)
  
  return(gap)
}

```

```{r}
synth.wdk2.paths <- function(
  unitID,
  fullname,
  begin,
  end,
  tr2,
  final,
  low,
  high
){
  
  data <- afripanel[afripanel$WBCode==unitID | afripanel$cont_dem_ind==1,]
  
  controls <- unique(data$WBCode[data$WBCode!=unitID&data$WBCode!="ETH"&data$WBCode!="SDN"])
  
  prep <- dataprep(
    foo=data, 
    predictors=c(
      "lngdpmadlag",
      "lngdpmadlag2",
      "lngdpmadlag3",
      "lngdpmadlag4",
      "lnpop",
      "ki",
      "openk",
      "civwar",
      "civwarend",
      "pwt_xrate",
      "pwt_xrate_lag1",
      "pwt_xrate_lag2",
      "pwt_xrate_lag3",
      "eximdiff",
      "eximdiff_lag1",
      "eximdiff_lag2",
      "wbank",
      "wbank_lag1",
      "wbank_lag2",
      "imfadj",
      "imfadj_lag1",
      "imfadj_lag2"
    ),
    dependent="lngdpmad",
    unit.variable="wbcode2",
    time.variable="year", 
    treatment.identifier=unitID, 
    controls.identifier=controls,          
    time.predictors.prior=c(begin:end),
    time.optimize.ssr=c(begin:tr2),
    time.plot=c(begin:final),
    unit.names.variable="WBCode"
  )
  
  out <- synth(prep)
  
  path.plot(synth.res=out, dataprep.res=prep,
            Ylab="Log GDP per capita", Legend=NA, tr.intake=tr2,
            Ylim=c(low,high) , Main=fullname
  )
  
  gap <- prep$Y1plot - (prep$Y0plot %*% 
                          out$solution.w)
  
  colnames(gap) <- unitID
  
  synth.table <- synth.tab(dataprep.res=prep, synth.res=out)
  
  print(xtable(synth.table$tab.w))
  
  print(xtable(synth.table$tab.v))
  
  tab <- cbind(prep$X1,prep$X0%*%out$solution.w)
  colnames(tab) <- c("Treated Unit","Synthetic Unit")
  print(tab)
  
  paths <- cbind(prep$Y1plot,prep$Y0plot%*%out$solution.w)
  
  return(list(paths,out))
}
```


```{r}
## Figure 2 Replication
paths <- synth.wdk2.paths("MLI", "Mali", 1980, 1990, 1991, 2008, 6, 8)  

plot(rownames(paths[[1]])[2:27],paths[[1]][2:27,1],
     type="l",ylim=c(6,8),ylab="Log GDP per capita",xlab="Time",lwd=3,bty="n")
lines(rownames(paths[[1]])[2:27],paths[[1]][2:27,2],lty=2,lwd=3)
legend("topleft",bty="n",legend=c("Mali","Synthetic counterfactual"),
       lty=c(1,2),lwd=c(3,3),cex=1,y.intersp=0.85)
abline(v=1991,lwd=2,lty=3)
graphics.off()

mali.weights <- round(paths[[2]]$solution.w,2)
country.names <- tapply(afripanel$Country,afripanel$wbcode2,unique)
rows <- unname(sapply(rownames(mali.weights),function(x){country.names[names(country.names)%in%x]}))
mali.weights <- data.frame(rows,mali.weights)
mali.weights <- mali.weights[order(mali.weights[,2],decreasing=T),]
mali.weights <- mali.weights[which(mali.weights[,2]!=0),]
colnames(mali.weights) <- c("Contribution","Weights")
```
```{r}
## Figure 2 Replication in-time placebo
paths <- synth.wdk2.paths("MLI", "Mali", 1980, 1990, 1991, 2008, 6, 8)  

plot(rownames(paths[[1]])[2:27],paths[[1]][2:27,1],
     type="l",ylim=c(6,8),ylab="Log GDP per capita",xlab="Time",lwd=3,bty="n")
lines(rownames(paths[[1]])[2:27],paths[[1]][2:27,2],lty=2,lwd=3)
legend("topleft",bty="n",legend=c("Mali","Synthetic counterfactual"),
       lty=c(1,2),lwd=c(3,3),cex=1,y.intersp=0.85)
abline(v=1991,lwd=2,lty=3)
graphics.off()

mali.weights <- round(paths[[2]]$solution.w,2)
country.names <- tapply(afripanel$Country,afripanel$wbcode2,unique)
rows <- unname(sapply(rownames(mali.weights),function(x){country.names[names(country.names)%in%x]}))
mali.weights <- data.frame(rows,mali.weights)
mali.weights <- mali.weights[order(mali.weights[,2],decreasing=T),]
mali.weights <- mali.weights[which(mali.weights[,2]!=0),]
colnames(mali.weights) <- c("Contribution","Weights")
```

```{r}
## Figure 2 Replication in-space placebo Burkina Faso
paths <- synth.wdk2.paths("BFA", "Burkina Faso", 1980, 1990, 1991, 2005, 6, 8)  

plot(rownames(paths[[1]])[2:26],paths[[1]][2:26,1],
     type="l",ylim=c(6,8),ylab="Log GDP per capita",xlab="Time",lwd=3,bty="n")
lines(rownames(paths[[1]])[2:26],paths[[1]][2:26,2],lty=2,lwd=3)
legend("topleft",bty="n",legend=c("Togo","Synthetic counterfactual"),
       lty=c(1,2),lwd=c(3,3),cex=1,y.intersp=0.85)
abline(v=1990,lwd=2,lty=3)
graphics.off()

togo.weights <- round(paths[[2]]$solution.w,2)
country.names <- tapply(afripanel$Country,afripanel$wbcode2,unique)
rows <- unname(sapply(rownames(togo.weights),function(x){country.names[names(country.names)%in%x]}))
togo.weights <- data.frame(rows,togo.weights)
togo.weights <-togo.weights[order(togo.weights[,2],decreasing=T),]
togo.weights <- togo.weights[which(togo.weights[,2]!=0),]
colnames(togo.weights) <- c("Contribution","Weights")
```

## Extensions

### Google Extension (CausalImpact)
```{r}
not_any_na <- function(x) all(!is.na(x))
show_impact_n <- function(
  Country,
  begin,
  end,
  treatYear
){
  data <- afripanel[which(afripanel$Country == Country), ]
  predictors=c(
      "lngdpmadlag",
      "lngdpmadlag2",
      "lngdpmadlag3",
      "lngdpmadlag4",
      "lnpop",
      "ki",
      "openk",
      "civwar",
      "civwarend",
      "pwt_xrate",
      "pwt_xrate_lag1",
      "pwt_xrate_lag2",
      "pwt_xrate_lag3",
      "eximdiff",
      "eximdiff_lag1",
      "eximdiff_lag2",
      "wbank",
      "wbank_lag1",
      "wbank_lag2",
      "imfadj",
      "imfadj_lag1",
      "imfadj_lag2"
  )

  outcome <- 'lngdpmad'
  time.points <- as.Date(as.character(data$year), "%Y")
  
  data <- data[, c(outcome, predictors)]
  data<-data[!is.na(data[outcome]),]
  data <- data %>% select_if(not_any_na)
  
  
  data <- zoo(data, time.points)
  data <- data[index(data) > as.Date(begin, '%Y') & index(data) < as.Date(end, '%Y')]
  
  nextYear <- as.Date(as.character(as.numeric(treatYear) + 1), "%Y")
  treatYear <- as.Date(treatYear, "%Y")
  
  start_date <- start(data)
  end_date <- end(data)
  
  pre.period <- as.Date(c(start_date, treatYear))
  post.period <- as.Date(c(nextYear, end_date))
  
  impact <- CausalImpact(data, 
                          pre.period, 
                          post.period, 
                          model.args = list(
                            niter = 1000, 
                            nseasons = 52)
                          )
  return(impact)
}
```

```{r}
impact <- show_impact_n('Mali', '1980', '2005', '1990')
plot(impact)
```
```{r}
impact <- show_impact_n('Mali', '1980', '2005', '1985')
plot(impact)
```
```{r}
impact <- show_impact_n('Burkina Faso', '1980', '2005', '1990')
plot(impact)
```





